### ISSUE TITLE
Add support for custom host name

### ISSUE THREAD

**Issue by subhojit-axl** [axelerant/db-docker#24]
There should be a provision to pass the remote host while building the image. Let's say, the user keeps multiple GitHub accounts, and there is a different private key associated with the account. The SSH config in the user's machine might look something like this:

```
Host github-personal.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_rsa_personal

Host github-work.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_rsa_work
```

The db-docker will look for only the selected ones, and it will fail. Therefore, user should have the ability to pass the host name, and therefore controlling which GitHub account is being referred.

**Comment by hussainweb** [comment]
Thanks, @subhojit-axl for creating this issue. I have been thinking more of this and wondering how we can achieve this with what we already have.

Since the setup you refer to is personal, it probably doesn't make sense to introduce some sort of mapping in the `composer.json` settings section. It might make more sense to implement this as a command-line option but would you type this in every time? Isn't that a lot of work?

That is why I am thinking our existing option to specify `docker-image-name` in the composer.json file addresses all the needs. You could set it to `ghcr.io/org/name` and then db-docker won't try to read the repo details at all. It will simply use that image name directly. See the [configuration](https://github.com/axelerant/db-docker#configuration) section to see the different possible options.

**Comment by subhojit-axl** [comment]
Hi @hussainweb Thanks for sharing your inputs. I was planning for a default command-line option. If not passed, it will pick up from one of the options.
However, I think I missed the `docker-image-name` option and its purpose in the README :| Thanks for pointing out. I will close this.
